#page title
page_title                                : Is That a Good Price                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=com.g33kdev.itagp
# presskit_download_link                    : https://emilbaehr.com                     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png
app_name: Is That a Good Price
app_price: Free
app_description: Track the price history of products so you know what's the best unit price.

enable_smart_app_banner: true



# Information About Yourself
your_name: g33kdev                                
# your_link                                 : https://emilbaehr.com                     
# your_city                                 : Copenhagen                                
email_address: support@g33kdev.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
# github_username                           : emilbaehr
# youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Track Unlimited Number of Products
    description                           : Organize price entries with different product categories.
    fontawesome_icon_name                 : infinity
    
  - title                                 : Track Unlimited Number of Entries
    description                           : A price entry includes date, merchant, name, units, quantities, price, discount types, note, and image.
    fontawesome_icon_name                 : infinity

  - title                                 : Automatic Unit Price
    description                           : Automatically calculates unit price for easy comparison.
    fontawesome_icon_name                 : magic

  - title                                 : Best Price Summary
    description                           : Automatically highlights the best unit price for each product.
    fontawesome_icon_name                 : funnel-dollar

  - title                                 : Dark Mode
    description                           : Dark and light theme based on system settings.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Merchant Autocomplete (Premium)
    description                           : Merchant entry autocompletes with previously entered merchants
    fontawesome_icon_name                 : magic

  - title                                 : Entry Name Autocomplete (Premium)
    description                           : Entry name autocompletes with previously entered names
    fontawesome_icon_name                 : magic

  - title                                 : Export to CSV (Premium)
    description                           : Export each entry list to CSV for additional analysis in Excel.
    fontawesome_icon_name                 : file-csv

  - title                                 : No Ads (Premium)
    description                           : Disable ads.
    fontawesome_icon_name                 : ad

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#000000"
feature_icons_background_color            : "#28cc9e"

social_icons_foreground_color             : "#000000"
social_icons_background_color             : "#28cc9e"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown